DigitalWPI/digitalwpi

- Gemfile
- Gemfile.lock
- app/models/etd.rb
- config/locales/hyrax.en.yml
- spec/features/create_etd_spec.rb
- spec/features/show_etd_spec.rb
- spec/models/etd_spec.rb
- spec/rails_helper.rb
Resolves #29  and also added gems required for test suite and modified the rails helper to use capybara and device.
> #29/active fedora noid

- public/robots.txt
> setting up robots to disallow search engine crawling

- config/initializers/hyrax.rb
- public/robots.txt
Deleted robots.txt from 
set ffmpeg = true in initializer/hyrax.rb
> Robots and video

- .fcrepo_wrapper
- config/fedora.yml
- config/solr.yml
> added fedora configuation to look at the environment variables

- Gemfile.lock
> updated rack gem

- db/seeds.rb
> Added seed file

- config/initializers/hyrax.rb
> Added geonames username

- config/initializers/noid_rails.rb
https://github.com/samvera/hyrax/issues/3128 
Implemented the suggested solution
> Fixes LDP Conflict issue

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/deploy/data.rb
- config/deploy/desk.rb
- config/deploy/production.rb
- config/deploy/qa.rb
- config/deploy/sandbox.rb
- lib/capistrano/tasks/debug_env.rake
- lib/capistrano/tasks/deploy_batch_loader.rake
- lib/capistrano/tasks/pull_mysql_data.rake
- lib/capistrano/tasks/pull_prod_data.rake
- lib/capistrano/tasks/pull_solr_data.rake
Capistrano configuration, Todos and Tasks
> Capistrano

- .travis.yml
- app/mailers/application_mailer.rb
- app/mailers/embargo_mailer.rb
- app/models/user.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/initializers/mailboxer.rb
- lib/tasks/UC_embargo_manager.rake
- spec/factories/generic_works.rb
- spec/mailers/embargo_mailer_spec.rb
Took inspiration form UC on the embargo email code, and tests. Got it to work in our system, just need a cron job that checks the embargo dates once per day.
Also the library team needs to decide the wording of the emails and recipients of the cemails.
Connects to #103
> Hyrax will now email users, also Embargo Emails set up

- app/controllers/catalog_controller.rb
- config/initializers/hyrax.rb
- spec/features/etd_search_meta_order_spec.rb
> resolves 107 and 69

- app/controllers/concerns/hydra/role_management/user_roles_behavior.rb
- app/forms/hyrax/student_work_form.rb
- app/models/ability.rb
- config/role_map.yml
- db/seeds.rb
- spec/factories/collections.rb
- spec/factories/student_work.rb
- spec/factories/users.rb
- spec/features/create_etd_spec.rb
- spec/features/create_generic_work_spec.rb
- spec/features/create_student_work_spec.rb
- spec/features/etd_search_meta_order_spec.rb
- spec/models/hyrax/ability_spec.rb
Connects #5 
added some groups to allow for library admins to give student works certain power to create and update things. more specific work will probably need to be done in the future but for now this solves the problem
> took away ability to create works for all users, added groups of express permissions

- app/controllers/catalog_controller.rb
Added and removed facets according to the changes suggested in the meeting. @aneslin Please review and comment on this PR once all the tests pass. @awscott Once Aaron posts his comments, please review and merge.
> Added and removed facets

- config/environments/production.rb
- config/initializers/devise.rb
- spec/factories/collection_type_participants.rb
- spec/factories/collections.rb
- spec/factories/collections_factory.rb
- spec/factories/collections_types.rb
- spec/factories/object_id.rb
- spec/factories/permission_template.rb
- spec/factories/permission_template_accesses.rb
- spec/models/collection_spec.rb
- spec/spec_helper.rb
Deleted shibboleth tests and added the tests related to collections
> Added tests related to collections

- .circleci/config.yml
- Gemfile
- Gemfile.lock
i wanted to add circleci for future deployment and because the hyrax community does circle
> integrate with circle ci

- spec/models/user_spec.rb
i just removed this useless line in the tests, merge if you want, or just close and destroy this branch
> this was to test circleci

- config/initializers/hyrax.rb
- config/initializers/sidekiq.rb
- config/redis.yml
- config/routes.rb
sidekiq and redis configuration to support task server
> task server sidekiq configuration

- config/authorities/resource_types.yml
closes #169 added manuscript resource type. very simple, aaron asked for this to be done
> #169 add manuscript resource type

- config/blacklight.yml
- config/deploy.rb
- config/initializers/hyrax.rb
- config/solr.yml
- db/seeds.rb
- lib/capistrano/tasks/first_deploy.rake
- spec/models/user_spec.rb
i think this should be merged, since our ansible stuff was merged as well, and we should have ansible push master now instead of task
> new variable changes for NFS, and more production ready inits

- Gemfile
- Gemfile.lock
- app/services/hyrax/analytics/matomo.rb
- app/views/_analytics.html.erb
- app/views/_head_tag_extras.html.erb
- config/analytics.yml
renders Matomo in every page on the application, but i double the downloads will be tracked. more work needed for that
> very basic analytics with matomo

- lib/tasks/move_works.rake
runs like 
`rails wpi:move_to_col -- --worktype=StudentWork --collection=iqp --where='{:id => "ww72bb48n"}'`
does StudentWork.where with the where and yada yada
> fixes #182, after deliberation decided to only add the task

- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
basically just changed so if the password is blank it does not auth. goes with the ansible pr on gitlab also
> fixed the email on prod issue

- lib/tasks/ingest_generic.rake
> Embargo files for works with batch-loader

- app/controllers/application_controller.rb
- app/controllers/callbacks_controller.rb
- config/authentication.yml
- config/initializers/devise.rb
- config/routes.rb
> Modify SSO code to suit our needs

- app/controllers/catalog_controller.rb
- app/views/hyrax/base/_attribute_rows.html.erb
- db/seeds.rb
- spec/features/etd_search_meta_order_spec.rb
Department displays as unit
added facets
> facets and stuff with update rspec

- app/assets/stylesheets/hyrax.scss
- app/controllers/common_objects_controller.rb
- app/controllers/hyrax/collections_controller.rb
- app/controllers/hyrax/etds_controller.rb
- app/controllers/hyrax/file_sets_controller.rb
- app/controllers/hyrax/generic_works_controller.rb
- app/controllers/hyrax/student_works_controller.rb
- app/presenters/permalinks_presenter.rb
- app/views/_permalink.html.erb
- app/views/layouts/hyrax.html.erb
- config/initializers/digital_wpi.rb
- config/routes.rb
taken from [UC's](https://github.com/uclibs/ucrate/pull/227) permalinks.
> Permalinks

- Capfile
- Gemfile
- Gemfile.lock
- config/honeybadger.yml
> Added honeybadger

- Gemfile
- Gemfile.lock
- config/application.rb
- config/environments/test.rb
- config/initializers/rack_attack.rb
> #190/rack attack

- app/controllers/registrations_controller.rb
> Fixed the registrations controller error

- app/controllers/application_controller.rb
- config/deploy.rb
- config/environments/production.rb
- lib/capistrano/tasks/first_deploy.rake
> Enable eager Load

- solr/config/solrconfig.xml
Added replication handler to solrconfig for us to be able to backup and restore solr using solr server. Once this PR is merged, when we deploy code to Prod, be sure copy solrconfig.xml into the right location and restart solr.
Fixes #140
> replication handler to support backup restore

- app/controllers/catalog_controller.rb
- app/models/etd.rb
- app/views/hyrax/base/_attribute_rows.html.erb
Fixes #232 
We need to run 
```ruby 
ActiveFedora::Base.reindex_everything
```
from console after we push these changes to QA/Prod.
> added advisor as a facet

- config/initializers/hyrax.rb
Fixes #237. Tested this on QA. I did get an email at ENV['MAILUSER'] email address.
> updated email address

- config/fedora.yml
- config/initializers/ntriples_reindexing.rb
> monkeypatch to run solr reindex successfully

- app/assets/stylesheets/wpi_custom.css.scss
- app/controllers/hyrax/etds_controller.rb
- app/controllers/hyrax/generic_works_controller.rb
- app/controllers/hyrax/student_works_controller.rb
- app/models/concerns/hyrax/solr_document/export.rb
- app/views/catalog/_index_list_default.html.erb
- app/views/hyrax/base/_citations.html.erb
- config/application.rb
- config/initializers/hyrax.rb
- config/initializers/mime_types.rb
- config/locales/etd.en.yml
- config/locales/generic_work.en.yml
- config/locales/hyrax.de.yml
- config/locales/hyrax.es.yml
- config/locales/hyrax.fr.yml
- config/locales/hyrax.it.yml
- config/locales/hyrax.pt-BR.yml
- config/locales/hyrax.zh.yml
- config/locales/student_work.en.yml
- lib/tasks/ingest_generic.rake
- lib/tasks/sample_works.json
Fixes #249, #239, #253, #244 and #246
> Few tiny issues

- app/assets/stylesheets/style.css.scss
- app/views/_controls.html.erb
> small fix on nav items

- app/views/static/help-page.html.erb
To fix #285 
Expect to see the content was updated
> update help page content

- app/views/static/help-page.html.erb
fix #287 
Lori corrected the contact info @email
> Lori correct one error

- app/views/static/collections.html.erb
save #293 
Change the collections' URL to absolute URL in " Browser by Collections"
> Change Collections'URL to absolute

- app/views/static/collections.html.erb
fix #295 issue
Add three subcollections under FPE.
Add a URL (https://digital.wpi.edu/collections/special_collection?locale=en) to "WPI Archives and History"
> Update bozlist 9 9 2020

- Gemfile
- Gemfile.lock
- app/controllers/catalog_controller.rb
- app/models/solr_document.rb
- config/routes.rb
fix #298 issue.
Add blacklight oai for Primo
Reference : https://github.com/projectblacklight/blacklight_oai_provider#customizing-listsets
> add Blacklight OAI

- app/controllers/catalog_controller.rb
- app/models/newlist_set.rb
- app/models/solr_document.rb
- app/views/static/project-centers.html.erb
fix the #301 
Add test code for testing oai
> add new class newlist_set.rb and add two test in solrDocument

- app/views/static/about-page.html.erb
#306 Update Emily's title to Digital Repository and Metadata Librarian
> update Emily's title

- app/views/static/project-centers.html.erb
fix #312 issue: add the new “category” (grey bar) to be added (under SOUTH PACIFIC): "WPI On-Campus and Other"
> add wpi on-campus and other as a new category under browse page

- app/views/static/help-page.html.erb
Added new session "Known Issues and Planned Enhancements" under "contact Us"on the Help page
> updateHelpPage for issue #319

- app/views/static/project-centers.html.erb
fix #333 new issue (the branch name should be addnewIQPcenter)
> add Taipei as a new IQP center

- app/controllers/controller_utils.rb
- app/controllers/hyrax/etds_controller.rb
- app/controllers/hyrax/generic_works_controller.rb
- app/controllers/hyrax/student_works_controller.rb
Fixes https://github.com/antleaf/wpi-repository-project/issues/44
Minor commit to remove repeating code.
> DRY of permalinks code

- lib/tasks/fix_collection_type.rake
fixes issue https://github.com/antleaf/wpi-repository-project/issues/37
The rake task needs to be run 
```
bundle exec rake wpi:fix_collection_type
```
It took about 30 hours to complete in the test environment.
> Rake task to fix collection type

- app/renderers/nested_attribute_renderer.rb
- app/renderers/nested_note_attribute_renderer.rb
fixes https://github.com/antleaf/wpi-repository-project/issues/16
https://github.com/DigitalWPI/digitalwpi/pull/379
> Renderer for admin notes

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/controllers/catalog_controller.rb
- app/controllers/saved_searches_controller.rb
- app/controllers/search_history_controller.rb
- app/models/search_builder.rb
- app/views/catalog/_search_form.html.erb
- config/routes.rb
Draft PR to address issues
* [#12- Resolve identified problems with Solr search functionality](https://github.com/antleaf/wpi-repository-project/issues/12)
* [#13 - Implement a fielded search form](https://github.com/antleaf/wpi-repository-project/issues/13)
This PR is work in progress
> Search improvements

- app/assets/stylesheets/style.css.scss
- app/views/hyrax/collections/show.html.erb
fixes https://github.com/antleaf/wpi-repository-project/issues/60
> Removed search and moved display of subcollections below collections

- app/controllers/catalog_controller.rb
Fixes https://github.com/antleaf/wpi-repository-project/issues/69
> Advanced search fields modification

- app/controllers/catalog_controller.rb
fixes https://github.com/antleaf/wpi-repository-project/issues/65
> Fix for all-fields to behave similar to search

- app/assets/javascripts/wpi_custom.js
- app/assets/stylesheets/wpi_custom.css.scss
- app/controllers/advanced_controller.rb
- app/views/advanced/_facet_limit.html.erb
- app/views/advanced/_fields.html.erb
- app/views/blacklight_advanced_search/_facet_limit.html.erb
- app/views/blacklight_range_limit/_range_limit_panel.html.erb
fixes https://github.com/antleaf/wpi-repository-project/issues/68
> show all facet fields in advanced search and fix range facet

- app/controllers/catalog_controller.rb
fixes https://github.com/antleaf/wpi-repository-project/issues/83
> Re-ordered search fields as per requirement

- app/controllers/catalog_controller.rb
fixes https://github.com/antleaf/wpi-repository-project/issues/69#issuecomment-1719634356
> Add sponsor and rename unit

- app/controllers/catalog_controller.rb
fixes https://github.com/antleaf/wpi-repository-project/issues/69#issuecomment-1746994760
> Removed sponsor field facet

- app/views/advanced/_advanced_search_form.html.erb
- app/views/advanced/_fields.html.erb
- app/views/advanced/index.html.erb
fixes https://github.com/antleaf/wpi-repository-project/issues/69
> Add search button under search tips

- app/views/advanced/_advanced_search_help.html.erb
- app/views/advanced/index.html.erb
- config/locales/hyrax.en.yml
Fixes https://github.com/antleaf/wpi-repository-project/issues/70
> Update to search tips

- app/controllers/catalog_controller.rb
- app/indexers/etd_indexer.rb
- app/indexers/generic_work_indexer.rb
- app/indexers/student_work_indexer.rb
- app/models/student_work.rb
- app/services/reindex_with_logs.rb
fixes https://github.com/antleaf/wpi-repository-project/issues/91
fixes https://github.com/antleaf/wpi-repository-project/issues/92
> license search, award search and facet

- app/controllers/catalog_controller.rb
- app/views/advanced/_advanced_search_help.html.erb
Reverts DigitalWPI/digitalwpi#498
> Revert "Feature/65 remove full text in advanced search"

- app/controllers/catalog_controller.rb
- app/indexers/etd_indexer.rb
- app/indexers/generic_work_indexer.rb
- app/indexers/indexer_helper.rb
- app/indexers/student_work_indexer.rb
- app/models/etd.rb
- app/models/generic_work.rb
- app/services/reindex_with_logs.rb
- app/views/advanced/_advanced_search_help.html.erb
fixes https://github.com/antleaf/wpi-repository-project/issues/65
fixes https://github.com/antleaf/wpi-repository-project/issues/92
> all fields advanced search and awards facet

- config/initializers/bulkrax.rb
fixes https://github.com/antleaf/wpi-repository-project/issues/85
> Fixed title required issue

- app/controllers/catalog_controller.rb
- app/views/catalog/_sort_and_per_page.html.erb
fixes https://github.com/antleaf/wpi-repository-project/issues/118#issuecomment-2127293809
> Bug fix/118 csv header with solr attr labels

- app/controllers/catalog_controller.rb
- config/locales/hyrax.en.yml
fixes https://github.com/antleaf/wpi-repository-project/issues/118#issuecomment-2168370614
> Add major, center and un sdg to download csv

- app/controllers/catalog_controller.rb
fixes https://github.com/antleaf/wpi-repository-project/issues/118
> Fix syntax error in add center major unsdg

- .env.template
- Dockerfile
- docker-compose.yml
fixes https://github.com/antleaf/wpi-repository-project/issues/101
> Fix docker build

- app/services/add_jpeg_to_works.rb
- lib/tasks/replace_tiff_with_jpg.rake
fixes https://github.com/antleaf/wpi-repository-project/issues/71
> Script and rake task to add jpeg to work containing tiff

- app/controllers/bookmarks_controller.rb
- app/controllers/catalog_controller.rb
- app/helpers/download_helper.rb
- app/views/bookmarks/_bookmark_actions.html.erb
This PR fixes https://github.com/antleaf/wpi-repository-project/issues/126
> Implements CSV download option to bookmarks

- app/forms/hyrax/etd_form.rb
- app/forms/hyrax/generic_work_form.rb
- app/forms/hyrax/student_work_form.rb
Fixes for:- https://github.com/antleaf/wpi-repository-project/issues/127
> Remove additional-fields button from work form

- app/models/solr_document.rb
- app/presenters/hyrax/etd_presenter.rb
- app/presenters/hyrax/generic_work_presenter.rb
- app/presenters/hyrax/student_work_presenter.rb
- app/presenters/hyrax/work_show_presenter.rb
fixes for:- https://github.com/antleaf/wpi-repository-project/issues/132
> Show all children on work page

- app/forms/hyrax/etd_form.rb
- app/forms/hyrax/generic_work_form.rb
- app/forms/hyrax/student_work_form.rb
- app/views/hyrax/base/_form_metadata.html.erb
fixes:- https://github.com/antleaf/wpi-repository-project/issues/127
> Refactor work form and revert some old codes

- app/views/advanced/_advanced_search_form.html.erb
- app/views/advanced/index.html.erb
fixes for:- https://github.com/antleaf/wpi-repository-project/issues/125
> change start over button position

- app/controllers/bookmarks_controller.rb
- app/helpers/download_helper.rb
fixes for:- https://github.com/antleaf/wpi-repository-project/issues/126
> Fix download document count

- app/services/add_jpeg_to_works.rb
fixes https://github.com/antleaf/wpi-repository-project/issues/71
> Return appropriate message for no parent works

- app/views/pdfviewer/index.html.erb
fixes https://github.com/antleaf/wpi-repository-project/issues/129#issuecomment-2435512003
> Renamed viewer metadata link to also support spotlight

- app/models/collection.rb
- config/initializers/nested_collection_query_service_override.rb
fixes for: https://github.com/antleaf/wpi-repository-project/issues/90#issuecomment-2500982191
> Fixes indexing time for sub-collections

- app/assets/javascripts/bookmark.js
- app/assets/stylesheets/wpi_custom.css.scss
- app/views/bookmarks/_bookmark_category_actions.html.erb
- app/views/bookmarks/_bookmark_category_url.html.erb
- app/views/bookmarks/_bookmark_category_url_modal.html.erb
- app/views/bookmarks/index.html.erb
fixes https://github.com/antleaf/wpi-repository-project/issues/126#issuecomment-2491733835
> Fixes spacing, button placement and url text for bookmarks

- app/services/add_jpeg_to_works.rb
fixes https://github.com/antleaf/wpi-repository-project/issues/71#issuecomment-2462491662
> Method to delete all tiff filesets and files

- app/services/hyrax/analytics/matomo.rb
- app/views/hyrax/file_sets/_actions.html.erb
- app/views/hyrax/file_sets/_single_use_links.html.erb
- app/views/hyrax/file_sets/media_display/_audio.html.erb
- app/views/hyrax/file_sets/media_display/_default.html.erb
- app/views/hyrax/file_sets/media_display/_image.html.erb
- app/views/hyrax/file_sets/media_display/_office_document.html.erb
- app/views/hyrax/file_sets/media_display/_video.html.erb
fixes for issue:- https://github.com/antleaf/wpi-repository-project/issues/133
> Fixes for matomo stats issue

- config/initializers/interpret_visibility_actor_override.rb
fixes for:- https://github.com/antleaf/wpi-repository-project/issues/139#event-16384497456
> Fix work visibility issue

- config/initializers/interpret_visibility_actor_override.rb
Fixes for Issue:-
https://github.com/antleaf-user/wpi-repository-project/issues/139#issuecomment-2786599299
> Fixes for work visibility error

- app/assets/stylesheets/wpi_custom.css.scss
- app/controllers/hyrax/admin/analytics/analytics_sync_logs_controller.rb
- app/controllers/hyrax/admin/analytics/work_reports_controller.rb
- app/controllers/hyrax/stats_controller.rb
- app/jobs/analytics_sync_job.rb
- app/models/analytics_sync_log.rb
- app/views/hyrax/admin/analytics/work_reports/_top_works.html.erb
- app/views/hyrax/admin/analytics/work_reports/_work_files.html.erb
- app/views/hyrax/admin/analytics/work_reports/index.html.erb
- config/routes.rb
- db/migrate/20250709024458_create_analytics_sync_logs.rb
- db/schema.rb
Fixes for issue
- https://github.com/antleaf-user/wpi-repository-project/issues/112#issuecomment-2260719659
**In-Progress**
> Implements filters and sync matomo stats
